### ISSUE TITLE
uninitialized constant when accessing through ruby on rails

### ISSUE THREAD

**Issue by drphaser** [blockcypher/ruby-client#13]
My ruby on rails model 'user' has a method addpaymentaddress but the blockcypher object cannot be initialized inside the active record model.

NameError: uninitialized constant User::BlockCypher

**Comment by genaromadrid** [comment]
Hey... This happens because Rails is looking for a folder `lib/block_cypher` since the class name is **B**lock**C**cyper but in this gem the folder name is `lib/blockcypher`. To fix it you have to set that up in your Gemfile as 
```ruby
gem 'blockcypher-ruby', '~> 0.2.0', :require => 'blockcypher'
```

@matthieu: i made a pull request to add that in the README file.

Cheers

**Comment by matthieu** [comment]
Merged, thanks!
